version: '3'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8008
    volumes:
      - .:/movie_web
    ports:
      - 8008:8008
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  redis:
    image: redis:alpine
  celery:
    build: ./
    command: celery -A movie_web worker -l info
    volumes:
      - .:/movie_web
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web
  celery-beat:
    build: ./
    command: celery -A movie_web beat -l info
    volumes:
      - .:/movie_web
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web
  
volumes:
  postgres_data: